mcs.metadata:
  componentName: A365 Demos
kind: AgentVariable
name: Listrowsfromselectedenvironment.organization
type: "{\"type\":\"string\",\"title\":\"Environment\",\"x-ms-dynamic-list\":{\"operationId\":\"GetOrganizations\",\"parameters\":{},\"itemsPath\":\"value\",\"itemValuePath\":\"Url\",\"itemTitlePath\":\"FriendlyName\"},\"description\":\"Choose an environment\",\"x-ms-visibility\":\"important\",\"x-ms-property-name-alias\":\"organization\"}"
defaultValue: https://org1649515c.crm17.dynamics.com